#!/usr/bin/php -q
<?php 
  require "config.php";

  $path = dirname(__FILE__);

  $task = $argv[1];

  if($task=="test"){
    runTest();
  } else if($task =="seed"){
    seed();
  } else if($task =="deploy"){
    concatJavascripts();
    system("cp -rf ./ /Library/WebServer/Documents/");
  } else if($task =="build"){
    concatJavascripts();
  } else if($task =="spec"){
    concatJavascripts();
    system("open $path/php/assets/spec/SpecRunner.html");
  } else{
    usage();
  }

  function usage(){
    echo "usage...\n";
    echo "./cake test :: run testcase\n";
    echo "./cake seed :: insert data to database\n";
  }

  function runTest(){
    system("php ./php/test/test.php");
  }

  function concatJavascripts(){

    system("cat LICENSE > php/assets/js/app.js");
    system("cat php/assets/app/models/*.js >> php/assets/js/app.js");
    system("cat php/assets/app/views/*.js >> php/assets/js/app.js");
    system("cat php/assets/app/controllers/*.js >> php/assets/js/app.js");
    system("cat php/assets/app/app.js >> php/assets/js/app.js");
  }

  function seed(){

    //insert user;
    $userControl = new UserCtrl();
    if($userControl->chkAccount("w3t")){
      $user = array(
      "user_account" => "w3t",
      "pwd" => "w3t",
      "first_name" => "W3Tester");
      $userControl->insertUser($user);
    }

    //insert receipts;
    $receiptControl = new ReceiptCtrl();
    $receipt = array(
      "store_account" => "Mc_NYU",
      "user_account" => "w3t",
      "tax" => 0.0875 ,
      "receipt_time" => "now()"
    );

    $items = array();

    array_push($items, array( 
           'item_id'=>'3',
           'item_name'=>'Harry-Potter - I', 
           'item_qty'=>1, 
           'item_price'=>10.99, 
           'item_discount'=>1));

    array_push($items, array( 
           'item_id'=>'4',
           'item_name'=>'Harry-potter - II', 
           'item_qty'=>2, 
           'item_price'=>39.99, 
           'item_discount'=>1));

    array_push($items, array( 
           'item_id'=>'5',
           'item_name'=>'Harry-potter - III', 
           'item_qty'=>5, 
           'item_price'=>19.99, 
           'item_discount'=>1));

    $flag = $receiptControl->insertReceipt($receipt,$items);
    if(!$flag){
      echo "insert fails\n";
    }
  }
?>
