#!/usr/bin/php -q
<?php 
  require "config.php";

  $root = dirname(__FILE__);

  $task = $argv[1];

  switch($task){
    case "test":
      runTest();
      break;
    case "build":
      buildJavascripts($root);
      break;
    case "seed":
      seed();
      break;
    case "spec":
      buildJavascripts();
      system("open $root/php/assets/spec/SpecRunner.html");
      break;
    case "watch":
      $css_path = $root."/php/assets/css";
      system("sass --watch $css_path:$css_path");
      break;
    case "db":
      $host = DB_HOST;
      $user = DB_USER;
      $pwd = DB_PWD;
      $db = DB_DBNAME;
      echo "mysql -h$host -u$user -p$pwd -D $db\n";
      break;
    default:
      usage();
  }

  function usage(){
    echo "usage:: ./cake [task]\n";
    echo "  test :: run testcase\n";
    echo "  seed :: insert data to database\n";
    echo "  spec :: run front-end test spec\n";
    echo "  watch :: watch scss file and compile into css\n";
    echo "  db :: show mysql console commend for refer...\n";
  }

  function runTest(){
    $path = dirname(__FILE__);
    system("phpunit $path/php/tests ");
  }

  function buildJavascripts($path){
    desc("concatenating javascript into app.js...");
    system("cat LICENSE > $path/php/assets/js/app.js");
    system("cat $path/php/assets/app/models/*.js >> $path/php/assets/js/app.js");
    system("cat $path/php/assets/app/views/*.js >> $path/php/assets/js/app.js");
    system("cat $path/php/assets/app/routers/*.js >> $path/php/assets/js/app.js");
    system("cat $path/php/assets/app/app.js >> $path/php/assets/js/app.js");
  }

  function seed(){

    desc("insert user");
    $userControl = new UserCtrl();
    if($userControl->chkAccount("w3t")){
      $user = array(
        "user_account" => "w3t",
        "pwd" => "w3t",
        "first_name" => "W3Tester",
      );
      $userControl->insertUser($user);
    }

    desc("insert receipt...");
    $receiptControl = new ReceiptCtrl();
    $receipt = array(
      "store_account" => "Mc_NYU",
      "user_account" => "w3t",
      "tax" => 8.75 ,
      "receipt_category" => "restaurant",
      "receipt_time" => "now()"
    );

    $items = array();

    array_push($items, array( 
           'item_name'=>'Big Mac', 
           'item_id'=>1,
           'item_qty'=>1, 
           'item_price'=>4.99, 
           'item_category' =>"food",
           'item_discount'=>1));

    array_push($items, array( 
           'item_name'=>'Salad', 
           'item_id'=>2,
           'item_qty'=>1, 
           'item_price'=>1.99, 
           'item_category' =>"food",
           'item_discount'=>1));

    array_push($items, array( 
           'item_name'=>'Medium drink', 
           'item_id'=>3,
           'item_qty'=>1, 
           'item_category' =>"drink",
           'item_price'=>1.99, 
           'item_discount'=>1));

    $flag = $receiptControl->insertReceipt($receipt,$items);
    if(!$flag){
      desc("insert fails");
    }
  }

  function desc($message){
    echo $message."\n";
  }
?>
